### ISSUE TITLE
Fielddata related error.

### ISSUE THREAD

**Issue by yangboz** [tuan3w/visual_search#10]
Finally, running 

```
http://localhost:5000/static/index.html
```
HTML working well ,but after  search ,the server thrown:

File "/home/user/anaconda3/envs/py2/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/user/anaconda3/envs/py2/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'search_phase_execution_exception', u'Fielddata is disabled on text fields by default. Set fielddata=true on [bin_sigs] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.')

Also the HTML console.log("Upload error").

**Comment by tuan3w** [comment]
Hi @yangboz ,
It seems you used wrong schema. `bin_sigs` field should be binary type. Run following command to create index with schema:
```bash
$ curl -XPUT http://${ES_ADDR}:9200/im_data -d @schema_es.json
```

**Comment by yangboz** [comment]
my fault, typo with "img_data" :-(

**Comment by yghcats** [comment]
@yangboz 
Hi, I also have your problem. How can I solve it?
thanks!

**Comment by yangboz** [comment]
@yghcats please my fork version: https://github.com/yangboz/visual_search

**Comment by ouceduxzk** [comment]
problem not solved, the schema_es.json already have bin_sigs with binary type
