### ISSUE TITLE
你好，vgg_weights文件下载不到，能传我这个文件嘛？谢谢

### ISSUE THREAD

**Issue by www6v** [tuan3w/visual_search#12]

**Comment by tuan3w** [comment]
Hi @www6v ,
Maybe I deleted this folder by accident when I was cleaning up my google drive. I cannot find any backup on my local disk right now. So sorry about that. BTW, anyone can help me share a copy :)

**Comment by www6v** [comment]
你好，现在vgg_weights这个文件找到了嘛？我这里想运行一下项目，但是vgg_weights文件找不到，项目跑不起来。

**Comment by tuan3w** [comment]
I updated READMe with pretrained mode. If you have any new problem, please raise a new issue.

**Comment by www6v** [comment]
Thanks a lot

**Comment by www6v** [comment]
thanks  a  lot.




At 2018-08-23 01:23:20, "Tuan Nguyen" <notifications@github.com> wrote:


I updated REA DMe with pretrained mode. If you have any new problem, please raise a new issue.
