### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by yghcats** [tuan3w/visual_search#16]
I run : mvn install 
An error message appears：
Warning: JAVA_HOME environment variable is not set.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.056 s
[INFO] Finished at: 2018-11-07T10:53:54+08:00
[INFO] Final Memory: 14M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/launchx-16-500/visual_search/elasticsearch). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by tuan3w** [comment]
Hi @yghcats,
Your information is vague. Can you provide more information? What exactly is your error logs ?

**Comment by yghcats** [comment]
@tuan3w 
I updated the error message.

**Comment by tuan3w** [comment]
Hi @yghcats ,
You are in wrong folder. You should cd to es-plugin folder, which contains a pom.xml file.
https://github.com/tuan3w/visual_search/tree/master/elasticsearch/es-plugin
The other problem might occur is that you need update JDK path. See https://maven.apache.org/install.html for more information how to install maven.

**Comment by yghcats** [comment]
@tuan3w 
Could you tell me what the following is for?
curl -XPUT http：// localhost：9200 / im_data -d @ schema_es.json

**Comment by tuan3w** [comment]
Elasticsearch requires mapping/schema for data (what kind of data will be stored in specific fields). If you don't specify that, Elasticsearch will store data as text field. This project stores feature of objects (as binary type) so we need define schema explicitly.
