### ISSUE TITLE
speed is very slow

### ISSUE THREAD

**Issue by pdc-kaminaga** [tuan3w/visual_search#18]
Thank you for providing a great program.
I want to process 1 million images.
I used tensorflow version 0.12.1 and EC2/p2.xlarge.
The speed is very slow.
Do you have a way to solve something?

**Comment by tuan3w** [comment]
If you still interest in developing a visual search engine, you can use ANN libraries like  faiss, annoy or [milvus](https://github.com/milvus-io/milvus) to filter top nearest images and use elasticsearch to refine your search results.

You might want to try [jinna](https://github.com/jina-ai/jina).
