### ISSUE TITLE
where is the file "elasticsearch.yml" ?

### ISSUE THREAD

**Issue by linzuk** [tuan3w/visual_search#2]
where is the file "elasticsearch.yml" ?
![aaaa](https://user-images.githubusercontent.com/27840457/27111121-8baa57a8-50e0-11e7-872b-f0fad60bd344.png)

**Comment by tuan3w** [comment]
Hi @linzuk,
There is no special config in `elasticsearch.yml`. So just remove that line, it will be ok.

**Comment by denzuko** [comment]
elastic search can be configured via the environment block in docker-compose.yml with environment variables that coraspond to the same  keys in the config file.
