### ISSUE TITLE
RequestError: TransportError(400, u'search_phase_execution_exception', u'Failed to compile inline script [hamming_score] using lang [native]')

### ISSUE THREAD

**Issue by xiesibo** [tuan3w/visual_search#4]
RequestError: TransportError(400, u'search_phase_execution_exception', u'Failed to compile inline script [hamming_score] using lang [native]')

**Comment by tuan3w** [comment]
You have to compile and install elasticsearch score plugin first. Follow the README for more details.
Thanks.
